version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    environment:
      - MAIL_SERVER_LOGIN=gorysilhouette@gmail.com
      - MAIL_SERVER_PASS=oxrmuspluglvohyr
      - TELEGRAM_TOKEN=1212136039:AAG-ijPCyPgpMOEUnU0fqeiwGbwaLbU_bVM
      - YANDEX_OAUTH=AgAAAAA6_rrpAATuwfnh0V0W50AqngZl7x_kCmk
      - YANDEX_FOLDER_ID=b1g6ovb59neq888uefhe
      - MY_CURRENT_URL=http://192.168.99.100:8000/
      - CURRENT_HOST=192.168.99.100
    image: sammyjankins/bookimage
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: shelf
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db