version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    environment:
      - MAIL_SERVER_LOGIN=
      - MAIL_SERVER_PASS=
      - TELEGRAM_TOKEN=
      - YANDEX_OAUTH=
      - YANDEX_FOLDER_ID=
      - MY_CURRENT_URL=
      - CURRENT_HOST=
    image: sammyjankins/bookimage
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: shelf
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db