# Generated by Django 3.1.1 on 2020-10-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre_tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='original_language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='year_of_creation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
