# Generated by Django 3.1.1 on 2020-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='parse_isbn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='ISBNp'),
        ),
    ]
