# Generated by Django 3.1.1 on 2020-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20200915_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
