# Generated by Django 3.1.1 on 2020-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20201017_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre_tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='original_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='year_of_creation',
            field=models.CharField(max_length=100),
        ),
    ]
