# Generated by Django 3.1.1 on 2020-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20201019_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Язык'),
        ),
    ]
