# Generated by Django 3.1.1 on 2020-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_novel_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
