# Generated by Django 3.1.1 on 2020-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20201019_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
