# Generated by Django 3.1.1 on 2020-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_book_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='row',
            field=models.CharField(choices=[('Первый', 'Первый'), ('Второй', 'Второй'), ('Третий', 'Третий'), ('Четвертый', 'Четвертый')], default='', max_length=100, verbose_name='Ряд'),
        ),
    ]
