# Generated by Django 3.1.1 on 2020-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_book_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
