# Generated by Django 3.1.1 on 2020-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0011_remove_book_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default='', verbose_name='Объем в страницах'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_of_cover',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Тип обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Год издания'),
        ),
    ]
