# Generated by Django 3.1.1 on 2020-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0012_auto_20201021_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_of_cover',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Тип обложки'),
        ),
    ]
