# Generated by Django 3.1.1 on 2020-10-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0013_auto_20201021_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.book', verbose_name='Last book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.shelf', verbose_name='Last shelf'),
        ),
    ]
