# Generated by Django 3.1.1 on 2020-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0014_auto_20201022_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
