# Generated by Django 3.1.1 on 2020-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0015_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcase',
            name='row_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookcase',
            name='section_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookcase',
            name='shelf_count',
            field=models.IntegerField(default=1),
        ),
    ]
