# Generated by Django 3.1.1 on 2020-11-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0016_auto_20201024_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_book',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.book', verbose_name='Last book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_shelf',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.shelf', verbose_name='Last shelf'),
        ),
    ]
